name: testing-actions
on: 
  pull_request:  
  push:
    branches:
      - main
      - staging

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout'
        uses: actions/checkout@v3

