name: testing-actions
on: 
  pull_request:  
    types: [ labeled ]

jobs:
  check-label:
    if: contains(github.event.pull_request.labels.*.name, 'test')
    runs-on: ubuntu-latest
    steps:
      - name: 'Testing labels'
        run: |
          echo "Hello!"
          exit 1