name: testing-actions
on: 
  pull_request:  
    types: [ labeled ]

jobs:
  check-label:
    if: ${{ github.event.label.name == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        run: echo Hello!